var NAVTREE_DATA =
[ [ "com.amazon.android.webkit", "reference/com/amazon/android/webkit/package-summary.html", [ [ "Interfaces", null, [ [ "AmazonDownloadListener", "reference/com/amazon/android/webkit/AmazonDownloadListener.html", null, null ], [ "AmazonFindListener", "reference/com/amazon/android/webkit/AmazonFindListener.html", null, null ], [ "AmazonGeolocationPermissions.Callback", "reference/com/amazon/android/webkit/AmazonGeolocationPermissions.Callback.html", null, null ], [ "AmazonValueCallback", "reference/com/amazon/android/webkit/AmazonValueCallback.html", null, null ], [ "AmazonWebChromeClient.CustomViewCallback", "reference/com/amazon/android/webkit/AmazonWebChromeClient.CustomViewCallback.html", null, null ], [ "AmazonWebChromeClient.OnCreateWindowCallback", "reference/com/amazon/android/webkit/AmazonWebChromeClient.OnCreateWindowCallback.html", null, null ] ]
, null ], [ "Classes", null, [ [ "AmazonApiLevels", "reference/com/amazon/android/webkit/AmazonApiLevels.html", null, null ], [ "AmazonConsoleMessage", "reference/com/amazon/android/webkit/AmazonConsoleMessage.html", null, null ], [ "AmazonCookieManager", "reference/com/amazon/android/webkit/AmazonCookieManager.html", null, null ], [ "AmazonCookieSyncManager", "reference/com/amazon/android/webkit/AmazonCookieSyncManager.html", null, null ], [ "AmazonGeolocationPermissions", "reference/com/amazon/android/webkit/AmazonGeolocationPermissions.html", null, null ], [ "AmazonHttpAuthHandler", "reference/com/amazon/android/webkit/AmazonHttpAuthHandler.html", null, null ], [ "AmazonJsPromptResult", "reference/com/amazon/android/webkit/AmazonJsPromptResult.html", null, null ], [ "AmazonJsResult", "reference/com/amazon/android/webkit/AmazonJsResult.html", null, null ], [ "AmazonSslErrorHandler", "reference/com/amazon/android/webkit/AmazonSslErrorHandler.html", null, null ], [ "AmazonWebBackForwardList", "reference/com/amazon/android/webkit/AmazonWebBackForwardList.html", null, null ], [ "AmazonWebChromeClient", "reference/com/amazon/android/webkit/AmazonWebChromeClient.html", null, null ], [ "AmazonWebHistoryItem", "reference/com/amazon/android/webkit/AmazonWebHistoryItem.html", null, null ], [ "AmazonWebKitFactories", "reference/com/amazon/android/webkit/AmazonWebKitFactories.html", null, null ], [ "AmazonWebKitFactory", "reference/com/amazon/android/webkit/AmazonWebKitFactory.html", null, null ], [ "AmazonWebResourceResponse", "reference/com/amazon/android/webkit/AmazonWebResourceResponse.html", null, null ], [ "AmazonWebSettings", "reference/com/amazon/android/webkit/AmazonWebSettings.html", null, null ], [ "AmazonWebStorage", "reference/com/amazon/android/webkit/AmazonWebStorage.html", null, null ], [ "AmazonWebView", "reference/com/amazon/android/webkit/AmazonWebView.html", null, null ], [ "AmazonWebView.HitTestResult", "reference/com/amazon/android/webkit/AmazonWebView.HitTestResult.html", null, null ], [ "AmazonWebViewClient", "reference/com/amazon/android/webkit/AmazonWebViewClient.html", null, null ], [ "AmazonWebViewDatabase", "reference/com/amazon/android/webkit/AmazonWebViewDatabase.html", null, null ], [ "AmazonWebViewFragment", "reference/com/amazon/android/webkit/AmazonWebViewFragment.html", null, null ] ]
, null ], [ "Enums", null, [ [ "AmazonConsoleMessage.MessageLevel", "reference/com/amazon/android/webkit/AmazonConsoleMessage.MessageLevel.html", null, null ], [ "AmazonWebSettings.LayoutAlgorithm", "reference/com/amazon/android/webkit/AmazonWebSettings.LayoutAlgorithm.html", null, null ], [ "AmazonWebSettings.ZoomDensity", "reference/com/amazon/android/webkit/AmazonWebSettings.ZoomDensity.html", null, null ] ]
, null ] ]
, null ] ]

;

